### ISSUE TITLE
Expose onWithOptions

### ISSUE THREAD

**Issue by jinjor** [elm/svg#20]
It seems `VirtualDom.Events.onWithOptions` works well on SVG elements too but currently it is not exposed by `Svg.Events` module. I'm not in a hurry but beginners don't know this function is available via `virtual-dom` package and they spends their time to find it. (I hope this issue helps them.)

**Comment by evancz** [comment]
The dev version exposes all the variants of the event attributes, so they should not need to hunt around once it is published!
