### ISSUE TITLE
Svg.Keyed.node is not working properly for all cases

### ISSUE THREAD

**Issue by Voronchuk** [elm/svg#26]
In Elm 18 the following code was working as intended:
```
g
        []
        [ renderUI state
        , Svg.Keyed.node "g"
            []
          <|
            List.map2 (prepareCellContext state)
                (List.map getCellKey mapList)
                (List.map (pointsToString << mapPolygonCorners << getCell) mapList)
        ]
```

Currently (Elm 19), this code puts the related DOM markup but the browsers (Chrome, Firefox) don't render it.

After some research I had to replace it with the low level `VirtualDom.keyedNodeNS "http://www.w3.org/2000/svg"`  which is working fine now:

```
g
        []
        [ renderUI state
        , VirtualDom.keyedNodeNS "http://www.w3.org/2000/svg"
            "g"
            []
          <|
            List.map2 (prepareCellContext state)
                (List.map getCellKey mapList)
                (List.map (pointsToString << mapPolygonCorners << getCell) mapList)
        ]
```

**Comment by architectcodes** [comment]
Thanks for this @Voronchuk! I can confirm that this is a problem and the workaround does the job.

I noticed that the node produced with `Svg.Keyed.node` has the SVG namespace defined as `.namespace` rather than `.namespaceURI`:

```js
$0.namespaceURI
// "http://www.w3.org/1999/xhtml"
$0.namespace 
// "http://www.w3.org/2000/svg"
```

A working node (such as `VirtualDom.keyedNodeNS "http://www.w3.org/2000/svg" "g"`) defines it as `.namespaceURI`:

```js
$0.namespace 
// undefined
$0.namespaceURI
// "http://www.w3.org/2000/svg"
```

**Comment by evancz** [comment]
Thanks for reporting this issue. I will do a patch soon that has the fix from https://github.com/elm/svg/commit/62b46c83280fa0297a814747929c4fa96a86cfef

**Comment by evancz** [comment]
Okay, patch should be available now. Thanks again!
